### ISSUE TITLE
Examine how long to keep things in redis

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter-backend#88]
We keep token details in redis to prevent having to look up details every time which is great for performance. But I've noticed I still get a hit on tokens that don't exist anymore. This can lead to confusing UX where a user thinks they're adding an existing token, but when Freighter goes to fetch the balance, it comes back with nothing.

Example of a token that was cleared after the last Testnet reset that still reports as existing: 
https://freighter-backend.stellar.org/api/v1/token-details/CDRSEYRV34EGWAS6VXZ63QBJLBJ3PJ5UYRSU5SY2NJLNWVHZ4FVSTL5K?pub_key=GBTYAFHGNZSTE4VBWZYAGB3SRGJEPTI5I4Y22KZ4JTVAN56LESB6JZOF&network=TESTNET

How long should we keep things in redis?

**Comment by aristidesstaffieri** [comment]
We chatted and decided that what we need here is to add a step in the testnet reset cycle to reset our redis cache, closing this in favor of the reset script ticket.
